// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaVirtual.Infrastructure.Configuration.Context;

#nullable disable

namespace PlataformaVirtual.Infrastructure.Migrations
{
    [DbContext(typeof(TramiteDbContext))]
    partial class TramiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tramite")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProcedimientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedimiento_id");

                    b.Property<Guid>("UsuarioCreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioEliminaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("expediente", "tramite");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoOperador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("foto_operador");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<Guid>("UsuarioCreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioEliminaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("operador", "tramite");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.OperadorCredencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("NumeroCredencial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_credencial");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<Guid>("UsuarioCreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioEliminaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("OperadorId");

                    b.ToTable("operador_credencial", "tramite");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.OperadorEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<Guid>("UsuarioCreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioEliminaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("OperadorId");

                    b.ToTable("operador_entidad", "tramite");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_documento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("segundo_apellido");

                    b.Property<Guid>("UsuarioCreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioEliminaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("persona", "tramite");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Procedimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("UsuarioCreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioEliminaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("procedimiento", "tramite");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("PlataformaVirtual.Domain.Entities.Procedimiento", "Procedimiento")
                        .WithMany("Expedientes")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PlataformaVirtual.Domain.ValueObjects.NumeroExpediente", "NroExpediente", b1 =>
                        {
                            b1.Property<Guid>("ExpedienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("nro_expediente");

                            b1.HasKey("ExpedienteId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("expediente", "tramite");

                            b1.WithOwner()
                                .HasForeignKey("ExpedienteId");
                        });

                    b.Navigation("NroExpediente")
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Operador", b =>
                {
                    b.HasOne("PlataformaVirtual.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.OperadorCredencial", b =>
                {
                    b.HasOne("PlataformaVirtual.Domain.Entities.Expediente", "Expediente")
                        .WithMany("Credenciales")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaVirtual.Domain.Entities.Operador", "Operador")
                        .WithMany("Credenciales")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.OperadorEntidad", b =>
                {
                    b.HasOne("PlataformaVirtual.Domain.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaVirtual.Domain.Entities.Operador", "Operador")
                        .WithMany("OperadorEntidades")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Persona", b =>
                {
                    b.OwnsOne("PlataformaVirtual.Domain.ValueObjects.DocumentoIdentidad", "NroDocumento", b1 =>
                        {
                            b1.Property<Guid>("PersonaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NroDocumento")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("nro_documento");

                            b1.Property<int>("TipoDocumentoId")
                                .HasColumnType("integer");

                            b1.HasKey("PersonaId");

                            b1.ToTable("persona", "tramite");

                            b1.WithOwner()
                                .HasForeignKey("PersonaId");
                        });

                    b.Navigation("NroDocumento")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Expediente", b =>
                {
                    b.Navigation("Credenciales");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Operador", b =>
                {
                    b.Navigation("Credenciales");

                    b.Navigation("OperadorEntidades");
                });

            modelBuilder.Entity("PlataformaVirtual.Domain.Entities.Procedimiento", b =>
                {
                    b.Navigation("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
